### ISSUE TITLE
Include released version in espidf

### ISSUE THREAD

**Issue by dhaval2017** [espressif/newlib-esp32#4] opened 2019-08-09 13:00 UTC
How to include this in existing espidf version?

**Comment by antmak** [comment] 2019-08-12 10:25
Hi @dhaval2017 !

This new newlib  (to be exact, `esp32-2019r1_newlib-3_0_0` branch of it) was included into the new toolchain `esp32-2019r1` directly. It's used in the latest master branch of IDF already. Please see https://docs.espressif.com/projects/esp-idf/en/latest/get-started/index.html#step-3-set-up-the-tools for more details how to install a modern toolchain (based on gcc8.2) to using with the modern IDF. 

The old newlib in idf's `components/newlib` is still left for compatibity with an old toolchain (gcc5.2 based)

**Comment by dhaval2017** [comment] 2019-08-12 12:31
esp32-2019r1 has regex library?

**Comment by antmak** [comment] 2019-08-13 05:17
It has C++'s `<regex>`. Unfortunately, C's `<regex.h>` doesn't work for now ( https://github.com/espressif/esp-idf/issues/2407 )

**Comment by dhaval2017** [comment] 2019-08-13 07:01
So no chance to use regex in c with espidf?

**Comment by antmak** [comment] 2019-08-13 10:41
Please try to take some 3rdparty lib like as https://github.com/kokke/tiny-regex-c for now.

regex.h will be fixed in the next toolchain release. The problem is we don't build `newlib/libc/posix/*` properly for the toolchain now.

**Comment by igrr** [comment] 2019-12-19 09:56
regex functions are available in esp-2019r2 toolchain release, which comes with IDF 4.1-dev (current master branch) (https://github.com/espressif/esp-idf/commit/c2db6a14c4404c6f50e096df459a096b47253f4a)

**Closed as completed by igrr** 2019-12-19 09:56 UTC
